apiVersion: tekton.dev/v1beta1

kind: Pipeline

metadata:

  name: terraform-cli-example

spec:

  workspaces:

  - name: default

  tasks:

  - name: terraform

    taskRef:

      name: terraform-cli

    workspaces:

    - name: default

      workspace: default

    params:

     - name: terraform-secret

       value: "terraform-secret"

     - name: ARGS

       value:

         - apply

         - "-auto-approve"
