apiVersion: tekton.dev/v1beta1

kind: Pipeline

metadata:

  name: terraform-cli-example

spec:

  workspaces:

  - name: nishitha5678-dev

  tasks:

  - name: terraform

    taskRef:

      name: terraform-cli

    workspaces:

    - name: nishitha5678-dev

      workspace: nishitha5678-dev

    params:

     - name: terraform-secret

       value: "terraform-secret"

     - name: ARGS

       value:

         - apply

         - "-auto-approve"
